const state={items:[],selected:new Set(),category:'all',query:'',intent:null};
const $=id=>document.getElementById(id);
const els={form:$('searchForm'),query:$('query'),source:$('source'),pageSize:$('pageSize'),gallery:$('gallery'),empty:$('emptyState'),status:$('status'),title:$('resultsTitle'),selectAll:$('selectAllBtn'),export:$('exportBtn'),categoryBar:$('categoryBar'),dialog:$('previewDialog'),previewImage:$('previewImage'),previewTitle:$('previewTitle'),previewMeta:$('previewMeta'),previewSource:$('previewSource'),closeDialog:$('closeDialog'),theme:$('themeBtn'),engineInfo:$('engineInfo'),googlePanel:$('googlePanel'),googleMain:$('googleMain'),googleQueries:$('googleQueries')};

els.form.addEventListener('submit',async e=>{e.preventDefault();const q=els.query.value.trim();if(!q)return;state.query=q;await runSearch(q)});
els.source.addEventListener('change',()=>{if(state.query)runSearch(state.query)});
els.selectAll.addEventListener('click',toggleSelectAll);
els.export.addEventListener('click',exportCatalog);
els.closeDialog.addEventListener('click',()=>els.dialog.close());
els.theme.addEventListener('click',()=>{document.body.classList.toggle('light');localStorage.setItem('rf-theme',document.body.classList.contains('light')?'light':'dark')});
if(localStorage.getItem('rf-theme')==='light')document.body.classList.add('light');
document.querySelectorAll('.chip').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.chip').forEach(b=>b.classList.remove('active'));btn.classList.add('active');state.category=btn.dataset.category;render()}));

async function runSearch(q){
  state.items=[];state.selected.clear();state.intent=classifyQuery(q);showIntent();showGoogleSearches(q,state.intent);
  const source=els.source.value;
  if(source==='google'){
    els.title.textContent='Fontes de apoio';els.status.textContent='Google Imagens definido como fonte principal. Escolha uma das pesquisas acima.';
    els.empty.hidden=false;els.empty.querySelector('h3').textContent='Pesquisas do Google prontas';els.empty.querySelector('p').textContent='Use os botões acima para abrir frente, traseira, lateral, interior, detalhes ou pesquisa técnica.';
    els.categoryBar.hidden=true;els.selectAll.disabled=true;updateExport();els.gallery.innerHTML='';return;
  }
  setLoading(true);
  try{
    const count=Number(els.pageSize.value)||40;
    const tasks=buildSourceTasks(source,state.intent,q,count);
    const batches=await Promise.all(tasks.map(x=>safeSource(x.name,x.run)));
    state.items=dedupe(batches.flat()).map(x=>({...x,score:relevanceScore(`${x.title} ${x.description||''}`,q,state.intent)})).filter(x=>x.score>=state.intent.minimumScore).sort((a,b)=>b.score-a.score).slice(0,count);
    els.title.textContent='Fontes de apoio';
    const working=[...new Set(state.items.map(x=>x.provider))];
    els.status.textContent=state.items.length?`${state.items.length} referências complementares encontradas em ${working.join(' e ')}.`:'Nenhuma referência complementar relevante. Continue pela busca principal do Google Imagens.';
    els.empty.hidden=state.items.length>0;els.categoryBar.hidden=state.items.length===0;els.selectAll.disabled=state.items.length===0;
    if(!state.items.length){els.empty.querySelector('h3').textContent='Sem resultados nas fontes de apoio';els.empty.querySelector('p').textContent='A pesquisa principal do Google Imagens continua disponível acima.'}
    render();
  }catch(err){console.error(err);els.status.textContent='As fontes de apoio falharam, mas a pesquisa principal do Google continua disponível.';els.empty.hidden=false}
  finally{setLoading(false)}
}

function showGoogleSearches(q,intent){
  const searches=buildGoogleQueries(q,intent);els.googlePanel.hidden=false;
  els.googleMain.href=googleUrl(searches[0].query);els.googleMain.textContent=`Abrir “${searches[0].label}”`;
  els.googleQueries.innerHTML='';
  searches.slice(1).forEach(item=>{const a=document.createElement('a');a.className='google-query';a.href=googleUrl(item.query);a.target='_blank';a.rel='noopener';a.innerHTML=`<strong>${escapeHtml(item.label)}</strong><span>${escapeHtml(item.query)}</span>`;els.googleQueries.appendChild(a)});
}
function googleUrl(q){return`https://www.google.com/search?tbm=isch&q=${encodeURIComponent(q)}`}
function buildGoogleQueries(q,intent){
  const base=q.trim();const common=[{label:'Pesquisa principal',query:`${base} reference images high resolution`},{label:'Frente',query:`${base} front view`},{label:'Traseira',query:`${base} rear view`},{label:'Lateral',query:`${base} side view`},{label:'Detalhes',query:`${base} close up details`}];
  if(intent.type==='veiculo')return[...common,{label:'Interior',query:`${base} interior dashboard`},{label:'Motor',query:`${base} engine bay`},{label:'Catálogo',query:`${base} brochure blueprint`}];
  if(intent.type==='colecionavel')return[...common,{label:'Ângulos 360°',query:`${base} action figure 360 turnaround`},{label:'Costas',query:`${base} back view toy`},{label:'Embalagem',query:`${base} original packaging`}];
  if(intent.type==='mecanica')return[...common,{label:'Vista explodida',query:`${base} exploded view`},{label:'Diagrama técnico',query:`${base} technical diagram`},{label:'Manual',query:`${base} service manual parts`}];
  if(intent.type==='arquitetura')return[...common,{label:'Fachada',query:`${base} facade`},{label:'Planta',query:`${base} floor plan elevation`},{label:'Estrutura',query:`${base} construction details`}];
  return[...common,{label:'Vista superior',query:`${base} top view`},{label:'Desenho técnico',query:`${base} technical drawing blueprint`}];
}

function classifyQuery(q){const s=normalize(q);const rules=[{type:'veiculo',label:'Veículo',icon:'🚗',test:/\b(carro|automovel|veiculo|chevrolet|fiat|ford|volkswagen|toyota|honda|omega|opala|gol|civic|truck|car|motorcycle|moto|caminhao)\b/,boost:['car','automobile','vehicle'],minimumScore:18},{type:'colecionavel',label:'Personagem ou colecionável',icon:'🦸',test:/\b(boneco|action figure|toy|figure|estatua|statue|personagem|superman|batman|marvel|anime)\b/,boost:['action figure','toy','statue'],minimumScore:22},{type:'mecanica',label:'Peça ou máquina',icon:'⚙️',test:/\b(motor|engine|maquina|machine|peca|part|engrenagem|gear|compressor|bomba|pump|torno)\b/,boost:['technical','diagram','manual'],minimumScore:18},{type:'arquitetura',label:'Arquitetura',icon:'🏛️',test:/\b(casa|predio|building|arquitetura|architecture|igreja|church|ponte|bridge|colonial|fachada)\b/,boost:['architecture','facade','plan'],minimumScore:16},{type:'espaco',label:'Espaço e astronomia',icon:'🚀',test:/\b(nasa|planeta|planet|lua|moon|marte|mars|galaxia|galaxy|space|espaco|foguete|rocket)\b/,boost:['NASA','space'],minimumScore:12},{type:'documento',label:'Manual ou documento técnico',icon:'📘',test:/\b(manual|catalogo|catalog|brochure|blueprint|planta|diagram|diagrama|esquema|technical)\b/,boost:['manual','catalog','diagram'],minimumScore:14}];const hit=rules.find(r=>r.test.test(s))||{type:'geral',label:'Pesquisa geral',icon:'🔎',boost:[],minimumScore:16};return{...hit,terms:coreTerms(q)}}
function showIntent(){els.engineInfo.textContent=`${state.intent.icon} Tipo detectado: ${state.intent.label} · Google Imagens é a fonte principal`}
function buildSourceTasks(source,intent,q,count){const each=Math.max(12,Math.ceil(count/2));if(source==='commons')return[{name:'Wikimedia Commons',run:()=>searchCommons(q,count,intent)}];if(source==='archive')return[{name:'Internet Archive',run:()=>searchArchive(q,count,intent)}];if(source==='nasa')return[{name:'NASA Images',run:()=>searchNasa(q,count)}];const tasks=[{name:'Wikimedia Commons',run:()=>searchCommons(q,intent.type==='documento'?each:count,intent)}];if(['documento','mecanica','veiculo'].includes(intent.type))tasks.push({name:'Internet Archive',run:()=>searchArchive(q,each,intent)});if(intent.type==='espaco')tasks.push({name:'NASA Images',run:()=>searchNasa(q,each)});return tasks}
async function safeSource(name,fn){try{return await fn()}catch(err){console.warn(`${name} indisponível`,err);return[]}}
async function searchCommons(q,count,intent){const main=intent.terms.join(' ')||q;const params=new URLSearchParams({action:'query',format:'json',origin:'*',generator:'search',gsrsearch:main,gsrnamespace:'6',gsrlimit:String(Math.min(Math.max(count*2,20),50)),prop:'imageinfo',iiprop:'url|extmetadata|size',iiurlwidth:'700'});const r=await fetch(`https://commons.wikimedia.org/w/api.php?${params}`);if(!r.ok)throw new Error(`Wikimedia ${r.status}`);const data=await r.json();return Object.values(data.query?.pages||{}).map((p,i)=>{const info=p.imageinfo?.[0]||{},meta=info.extmetadata||{},title=(p.title||'').replace(/^File:/,'');const description=stripHtml(meta.ImageDescription?.value||'');return{id:`wc-${p.pageid||i}`,title,description,thumb:info.thumburl||info.url,full:info.url||info.thumburl,sourceUrl:info.descriptionurl||info.url,creator:stripHtml(meta.Artist?.value)||'Autor não informado',license:meta.LicenseShortName?.value||'Licença não informada',provider:'Wikimedia Commons',width:info.width,height:info.height,category:suggestCategory(`${title} ${description}`,q)}}).filter(x=>x.thumb)}
async function searchArchive(q,count,intent){const term=escapeArchive(`${intent.terms.join(' ')||q} ${intent.boost.slice(0,2).join(' ')}`);const params=new URLSearchParams({q:`(${term}) AND (mediatype:image OR mediatype:texts)`,fl:'identifier,title,creator,mediatype,description,subject',rows:String(Math.min(Math.max(count*2,20),50)),output:'json'});const r=await fetch(`https://archive.org/advancedsearch.php?${params}`);if(!r.ok)throw new Error(`Archive ${r.status}`);const data=await r.json();return(data.response?.docs||[]).map((x,i)=>({id:`ia-${x.identifier||i}`,title:cleanValue(x.title)||x.identifier,description:`${cleanValue(x.description)} ${cleanValue(x.subject)}`,thumb:`https://archive.org/services/img/${encodeURIComponent(x.identifier)}`,full:`https://archive.org/services/img/${encodeURIComponent(x.identifier)}`,sourceUrl:`https://archive.org/details/${encodeURIComponent(x.identifier)}`,creator:cleanValue(x.creator)||'Autor não informado',license:'Verifique na origem',provider:'Internet Archive',category:suggestCategory(`${cleanValue(x.title)} ${cleanValue(x.description)}`,q)}))}
async function searchNasa(q,count){const r=await fetch(`https://images-api.nasa.gov/search?q=${encodeURIComponent(q)}&media_type=image&page_size=${Math.min(count,100)}`);if(!r.ok)throw new Error(`NASA ${r.status}`);const data=await r.json();return(data.collection?.items||[]).map((x,i)=>{const d=x.data?.[0]||{},link=x.links?.[0]||{};return{id:`nasa-${d.nasa_id||i}`,title:d.title||'Sem título',description:d.description||'',thumb:link.href,full:link.href,sourceUrl:`https://images.nasa.gov/details/${encodeURIComponent(d.nasa_id||'')}`,creator:d.center||'NASA',license:'Verifique as regras da NASA',provider:'NASA Images',category:'principal'}}).filter(x=>x.thumb)}
function coreTerms(q){const stop=new Set(['foto','fotos','imagem','imagens','de','da','do','das','dos','um','uma','o','a','os','as','para','com','quero','achar','buscar']);return normalize(q).split(/\s+/).filter(w=>w.length>2&&!stop.has(w))}
function relevanceScore(text,q,intent){const hay=normalize(text),terms=intent.terms;if(!terms.length)return 1;let score=0,hits=0;terms.forEach(t=>{if(hay.includes(t)){hits++;score+=14}});if(!hits)return 0;if(hits===terms.length)score+=28;if(hay.includes(terms.join(' ')))score+=35;intent.boost.forEach(b=>{if(hay.includes(normalize(b)))score+=6});if(/scan|book|page|manuscript/.test(hay)&&!['documento','mecanica'].includes(intent.type))score-=24;return score}
function normalize(s=''){return String(s).toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,' ').trim()}
function escapeArchive(q){return q.split(/\s+/).filter(Boolean).map(w=>`(${w.replace(/["()]/g,'')})`).join(' AND ')}
function cleanValue(v){return Array.isArray(v)?v.join(', '):(v==null?'':String(v))}
function dedupe(items){const seen=new Set();return items.filter(x=>{const key=normalize(x.sourceUrl||x.thumb||x.title);if(!key||seen.has(key))return false;seen.add(key);return true})}
function suggestCategory(text,q){const s=normalize(`${text} ${q}`);if(/interior|dashboard|painel|cabine|cockpit|seat|banco/.test(s))return'interior';if(/drawing|blueprint|diagram|technical|manual|catalog|brochure|planta/.test(s))return'tecnico';if(/detail|close|wheel|roda|engine|motor|texture|detalhe|part|peca/.test(s))return'detalhes';return'principal'}
function stripHtml(v=''){const d=document.createElement('div');d.innerHTML=v;return d.textContent.trim()}
function setLoading(on){if(on){els.empty.hidden=true;els.gallery.innerHTML='<div class="loader">Buscando referências complementares…</div>';els.selectAll.disabled=true;els.export.disabled=true}else if(!state.items.length)els.gallery.innerHTML=''}
function render(){const items=state.category==='all'?state.items:state.items.filter(x=>x.category===state.category);els.gallery.innerHTML='';items.forEach(item=>{const card=document.createElement('article');card.className=`card${state.selected.has(item.id)?' selected':''}`;card.innerHTML=`<span class="license">${escapeHtml(item.provider)}</span><img class="thumb" loading="lazy" src="${escapeAttr(item.thumb)}" alt="${escapeAttr(item.title)}"><div class="card-body"><div class="card-title">${escapeHtml(item.title)}</div><div class="card-meta">${escapeHtml(item.creator)}</div><div class="card-controls"><select><option value="principal">Principal</option><option value="detalhes">Detalhes</option><option value="interior">Interior</option><option value="tecnico">Técnico</option><option value="outros">Outros</option></select><button class="pick${state.selected.has(item.id)?' active':''}">✓</button></div></div>`;const img=card.querySelector('.thumb');img.addEventListener('error',()=>card.remove(),{once:true});const select=card.querySelector('select');select.value=item.category;select.addEventListener('change',e=>{item.category=e.target.value});card.querySelector('.pick').addEventListener('click',()=>toggleItem(item.id));img.addEventListener('click',()=>preview(item));els.gallery.appendChild(card)});updateExport()}
function toggleItem(id){state.selected.has(id)?state.selected.delete(id):state.selected.add(id);render()}
function toggleSelectAll(){const visible=state.category==='all'?state.items:state.items.filter(x=>x.category===state.category);const all=visible.length&&visible.every(x=>state.selected.has(x.id));visible.forEach(x=>all?state.selected.delete(x.id):state.selected.add(x.id));render()}
function updateExport(){els.export.disabled=state.selected.size===0;els.export.textContent=state.selected.size?`Exportar catálogo (${state.selected.size})`:'Exportar catálogo'}
function preview(item){els.previewImage.src=item.full;els.previewTitle.textContent=item.title;els.previewMeta.textContent=`${item.creator} • ${item.license} • ${item.provider}`;els.previewSource.href=item.sourceUrl;els.dialog.showModal()}
function exportCatalog(){const selected=state.items.filter(x=>state.selected.has(x.id));const rows=selected.map(x=>`<article><img src="${escapeAttr(x.thumb)}"><h2>${escapeHtml(x.title)}</h2><p>${escapeHtml(x.provider)}</p><a href="${escapeAttr(x.sourceUrl)}">Abrir origem</a></article>`).join('');const html=`<!doctype html><html lang="pt-BR"><meta charset="utf-8"><title>ReferenceForge</title><body><h1>${escapeHtml(state.query)}</h1>${rows}</body></html>`;const blob=new Blob([html],{type:'text/html;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`referenceforge-${slug(state.query)}.html`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function slug(s){return normalize(s).replace(/\s+/g,'-')}
function escapeHtml(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function escapeAttr(s=''){return escapeHtml(s)}